name: MineGuildConnector
version: ${project.version}
description: MineGuildConnectorPlugin
authors: [Kekshaus]
main: de.linzn.mineGuild.connector.MineGuildConnectorPlugin
load: POSTWORLD
depend: [MineSuiteCore, Vault]
api-version: 1.13
commands:
  guild:
    description: Guild Command
  gc:
    description: Guild chat command
permissions:
    mineguild.all:
        description: Alle Guild permissions
        children:
            mineguild.help: true
            mineguild.create: true
            mineguild.disband: true
            mineguild.info: true
            mineguild.members: true
            mineguild.accept: true
            mineguild.deny: true
            mineguild.invite: true
            mineguild.leave: true
            mineguild.kick: true
            mineguild.list: true
            mineguild.home: true
            mineguild.deposit: true
            mineguild.withdraw: true
            mineguild.chat: true
            mineguild.setrang: true
    mineguild.help:
        default: op
    mineguild.create:
        default: op
    mineguild.disband:
        default: op
    mineguild.info:
        default: op
    mineguild.members:
        default: op
    mineguild.accept:
        default: op
    mineguild.deny:
        default: op
    mineguild.invite:
        default: op
    mineguild.leave:
        default: op
    mineguild.kick:
        default: op
    mineguild.list:
        default: op
    mineguild.home:
        default: op
    mineguild.deposit:
        default: op
    mineguild.withdraw:
        default: op
    mineguild.chat:
        default: op
    mineguild.setrang:
        default: op